<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Rede D'Or S&atilde;o Luiz</title>
</head>
<body>

<h1>Rede D'Or S&atilde;o Luiz</h1>

<ul><b>Client</b>
<li><a href="http://192.168.218.168/rest/rededor/clientrededor/">Client Exemplo</a></li>
</ul>

<ul><b>WSDL</b>
<li><a href="http://192.168.218.168/rest/wsdl/rededor.wsdl">Baixe a WSDL (rededor.wsdl)</a></li>
</ul>

<ul><b>Documenta&ccedil;&atilde;o padr&atilde;o/exemplo SOAP/REST</b>
<li><a href="http://192.168.218.168/rest/appfiles/docs/webservice_doc_soap_1_1.doc">Documenta&ccedil;&atilde;o padr&atilde;o/exemplo SOAP</a></li>
<li><a href="http://192.168.218.168/rest/appfiles/docs/webservice_doc_rest_1_1.doc">Documenta&ccedil;&atilde;o padr&atilde;o/exemplo REST</a></li>
</ul>

</body>
</html>
