<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rhow="http://xmlns.oracle.com/orawsv/RHOWS/AMX_RS_DADOS_CADASTRAIS">
   <soapenv:Header />
   <soapenv:Body>
      <rhow:AMX_RS_DADOS_CADASTRAISInput>
         <rhow:P_IDENTIFICACAO-VARCHAR2-IN>IHUNTERX14</rhow:P_IDENTIFICACAO-VARCHAR2-IN>
         <!--Optional:-->
         <rhow:P_ID-NUMBER-IN>?</rhow:P_ID-NUMBER-IN>
         <!--Optional:-->
         <rhow:P_CPF-NUMBER-IN>?</rhow:P_CPF-NUMBER-IN>
         <!--Optional:-->
         <rhow:P_TIPO_COLAB-VARCHAR2-IN>?</rhow:P_TIPO_COLAB-VARCHAR2-IN>
         <rhow:P_RESULT-XMLTYPE-OUT />
         <!--Optional:-->
         <rhow:P_SITUACAO-VARCHAR2-IN>A</rhow:P_SITUACAO-VARCHAR2-IN>
         <!--Optional:-->
         <rhow:P_DATA_ADMISSAO_ATE-VARCHAR2-IN>?</rhow:P_DATA_ADMISSAO_ATE-VARCHAR2-IN>
         <!--Optional:-->
         <rhow:P_DATA_ADMISSAO-VARCHAR2-IN>?</rhow:P_DATA_ADMISSAO-VARCHAR2-IN>
         <!--Optional:-->
         <rhow:P_DATA_DEMISSAO_ATE-VARCHAR2-IN>?</rhow:P_DATA_DEMISSAO_ATE-VARCHAR2-IN>
         <!--Optional:-->
         <rhow:P_DATA_DEMISSAO-VARCHAR2-IN>?</rhow:P_DATA_DEMISSAO-VARCHAR2-IN>
      </rhow:AMX_RS_DADOS_CADASTRAISInput>
   </soapenv:Body>
</soapenv:Envelope>
