<?php

for($x = 0; $x < count($view_list); $x++) {
  echo '<BR> STATUS => ' . $view_list[$x]->STATUS;
  echo '<BR> NOME  => ' . $view_list[$x]->NOME;
  echo '<BR> SOLICITANTE_RESP  => ' . $view_list[$x]->SOLICITANTE_RESP;
  echo '<BR> COD_AREA_ATUACAO  => ' . $view_list[$x]->COD_AREA_ATUACAO;
  echo '<BR> DESC_AREA_ATUACAO  => ' . $view_list[$x]->DESC_AREA_ATUACAO;
  echo '<BR> CARGO  => ' . $view_list[$x]->CARGO;
  echo '<BR> DESC_CARGO  => ' . $view_list[$x]->DESC_CARGO;
  echo '<BR> EMPRESA  => ' . $view_list[$x]->EMPRESA;
  echo '<BR> DESC_EMPRESA  => ' . $view_list[$x]->DESC_EMPRESA;
  echo '<BR> DATA_INICIO  => ' . $view_list[$x]->DATA_INICIO;
  echo '<BR> DESCRICAO  => ' . $view_list[$x]->DESCRICAO;
  echo '<BR> OBSERVACOES  => ' . $view_list[$x]->OBSERVACOES;
  echo '<BR> GESTOR  => ' . $view_list[$x]->GESTOR;
  echo '<BR> TEL_GESTOR  => ' . $view_list[$x]->TEL_GESTOR;
  echo '<BR> TIPO_CONTRATO  => ' . $view_list[$x]->TIPO_CONTRATO;
  echo '<BR> VAGAS  => ' . $view_list[$x]->VAGAS;
  echo '<BR> ESTADO  => ' . $view_list[$x]->ESTADO;
  echo '<BR> CIDADE  => ' . $view_list[$x]->CIDADE;
  echo '<BR> LOCAL_TRABALHO  => ' . $view_list[$x]->LOCAL_TRABALHO;
  echo '<BR> PERFIL_PROFISSIONAL  => ' . $view_list[$x]->PERFIL_PROFISSIONAL;
  echo '<BR> FAIXA_SALARIAL  => ' . $view_list[$x]->FAIXA_SALARIAL;
  echo '<BR> MOTIVO_CONTRATO  => ' . $view_list[$x]->MOTIVO_CONTRATO;
  echo '<BR> KEY_DATA  => ' . $view_list[$x]->KEY_DATA;
  echo '<BR> COD_INTEGRACAO  => ' . $view_list[$x]->COD_INTEGRACAO;
  echo '<BR> OBSERVACAO  => ' . $view_list[$x]->OBSERVACAO;
}

 ?>
<body>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                </div>
</body>
