
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="../appfiles/css/jquery.dataTables.css">
<link rel="stylesheet" href="../appfiles/bootstrap/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="../appfiles/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="../appfiles/css/ionicons.min.css">
<!-- DataTables -->
<link rel="stylesheet" href="../appfiles/plugins/datatables/dataTables.bootstrap.css">
<!-- Theme style -->
<link rel="stylesheet" href="../appfiles/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="../appfiles/dist/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">


<script type="text/javascript" language="javascript" src="../appfiles/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="../appfiles/js/jquery.dataTables.js"></script>
<script src="../appfiles/js/jquery.min.js"></script>

<script>
$(document).ready(function() {
  var dataTable = $('#employee-grid').DataTable( {
    "processing": true,
    "serverSide": true,
    "ajax":{
      url :"/frameweb/pacexpress/reportlog", // json datasource
      type: "post",  // method  , by default get
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3"></th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");

      }
    }
  } );

  $("#employee-grid_filter").css("display","none");  // hiding global search box
  $('.search-input-select').on( 'change', function () {   // for select box
    var i =$(this).attr('data-column');
    var v =$(this).val();
    dataTable.columns(i).search(v).draw();
  } );
  $('.search-input-text').on( 'keyup', function () {   // for text boxes
      var i =$(this).attr('data-column');  // getting column index
      var v =$(this).val();  // getting search input value
      dataTable.columns(i).search(v).draw();
  } );


  $("#btn").click(function(){
      $.post("/frameweb/pacexpress/detaillog",
         {
         },
   function(response,status){
       $("#bingo").html(response);
       $("#form")[0].reset();
    });
   });

   $("#btn2").click(function(){
       $.post("/frameweb/pacexpress/teste",
          {
          },
    function(response,status){
        $("#bingo").html(response);
        $("#form")[0].reset();
     });
    });

} );
</script>
<style type="text/css">
    .bs-example{
            margin: 20px;
    }
</style>
</head>
<body>

<button type="button" id="btn" class="btn btn-info" data-toggle="modal" data-target="#myModal">Send Data</button>
<button type="button" id="btn2" class="btn btn-info" data-toggle="modal" data-target="#myModal">Send Data2</button>


<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">MyModal</h4>
      </div>
      <div class="modal-body">
        <div id="bingo"></div>

      </div>
    </div>
   </div>
</div>

<script src="../appfiles/plugins/jQuery/jQuery-2.1.4.min.js"></script>
   <!-- Bootstrap 3.3.5 -->
   <script src="../appfiles/bootstrap/js/bootstrap.min.js"></script>
   <!-- DataTables -->
   <script src="../appfiles/plugins/datatables/jquery.dataTables.min.js"></script>

   <script src="../appfiles/plugins/datatables/dataTables.bootstrap.min.js"></script>
   <!-- SlimScroll -->
   <script src="../appfiles/plugins/slimScroll/jquery.slimscroll.min.js"></script>
   <!-- FastClick -->
   <script src="../appfiles/plugins/fastclick/fastclick.min.js"></script>
   <!-- AdminLTE App -->
   <script src="../appfiles/dist/js/app.min.js"></script>
   <!-- AdminLTE for demo purposes -->
   <script src="../appfiles/dist/js/demo.js"></script>


</body>
</html>
