<?php
echo json_encode($view_list);

/*echo '[';
echo '{';
$EMPLOYMENTID = $view_list_candidatos[0]->EMPLOYMENTID;
if ($EMPLOYMENTID == 'denied') {
    echo '"access":'.$view_list_candidatos[0]->EMPLOYMENTID.'';
} else {
        for($x = 0; $x < count($view_list_candidatos); $x++) {
            echo '"employmentId":'.$view_list_candidatos[$x]->EMPLOYMENTID.',';
            echo '"employee":{';
            echo '"cpf":{';
            echo '"number":"'.substr($view_list_candidatos[$x]->CPF, 0, -2).',';
            echo '"digit":"' .substr($view_list_candidatos[$x]->CPF, -2);
            echo '},';
            echo '"rg":{';
            echo '"number":"9955461",';
            echo '"digit":"4",';
            echo '"issuingAgency":"SSP‐PR",';
            echo '"stateRg":"PR",';
            echo '"dateOfIssueRg":{';
            echo '"date":"2012‐02‐03 00:00:00",';
            echo '"timezone_type":3,';
            echo '"timezone":"America\/Sao_Paulo"';
            echo '}';
            echo '}';
        }
}
echo '}';
echo ']';*/
//$inputJSON = file_get_contents('php://input');
//echo $inputJSON;


?>
